SalaJuntasFrontend/Controllers/AreasController.cs
using ApiSalaJuntas.Model.DTOS.Areas;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SalaJuntasFrontend.Servicios;

namespace SalaJuntasFrontend.Controllers
{
    [Authorize]
    public class AreasController : Controller
    {
        public HttpsLocalService localServiceSSL = new HttpsLocalService();

        private readonly IMapper mapper;
        private readonly IConfiguration _configuration;

        public AreasController(IMapper mapper, IConfiguration configuration)
        {
            this.mapper = mapper;
            _configuration = configuration;
        }

        // GET: AreasController
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public async Task<ActionResult<List<AreaDTO>>> TodosAreas()
        {
            //var tokenClaim = HttpContext.User.Claims.Where(x => x.Type == "Token").FirstOrDefault();
            //if (tokenClaim == null)
            //{
            //    ///Enviar mensaje de error
            //    return Json("No se encuentra el TOKEN");
            //}

            HttpClient client = localServiceSSL.VotarSSL();
            var url = _configuration.GetValue<string>("ConnectionStrings:API") + "/api/areas";

            try
            {
                HttpResponseMessage response = await client.GetAsync(url);
                var r = response.StatusCode;
                if (r == System.Net.HttpStatusCode.OK)
                {
                    string responseBody = await response.Content.ReadAsStringAsync();
                    // Above three lines can be replaced with new helper method below
                    // string responseBody = await client.GetStringAsync(uri);
                    var ListAreas = JsonConvert.DeserializeObject<List<AreaDTO>>(responseBody).ToList();
                    return new JsonResult(new { Data = ListAreas });

                }
                //Si nos responde el api not found significa que no encontro una lista de evntos para esa fecha
                return new List<AreaDTO>();
            }
            catch (HttpRequestException e)
            {
                return BadRequest(e.Message);
            }

        }


        // GET: AreasController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        /// <summary>
        /// Nos conectamos con el api para guardar el area
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult<RespuestaAreaDTO>> CrearAreaAPI([FromBody] AreaCreacionDTO areaCreacionDTO)
        {
            var tokenClaim = HttpContext.User.Claims.Where(x => x.Type == "Token").FirstOrDefault();
            if (tokenClaim == null)
            {
                ///Enviar mensaje de error
                return Json("No se encuentra el TOKEN");
            }


            //Enviar al api la informacion
            HttpClient client = localServiceSSL.VotarSSL(tokenClaim.Value);
            var url = _configuration.GetValue<string>("ConnectionStrings:API") + "/api/areas";
            try
            {
            
                string jsonArea = JsonConvert.SerializeObject(areaCreacionDTO);
                var content = new StringContent(jsonArea, System.Text.Encoding.UTF8, "application/json");
                var response = await client.PostAsync(url, content);
                if (response.IsSuccessStatusCode)
                {
                    string responseBody = await response.Content.ReadAsStringAsync();
                    var areaRespuestaDTO = JsonConvert.DeserializeObject<RespuestaAreaDTO>(responseBody);
                    return areaRespuestaDTO;
                }
                else
                {
                    return new RespuestaAreaDTO()
                    {
                        mensaje = "No establecio conexion con el api",
                        codigoEstatus = 404,
                        icono = "info",
                    };
                }
            }
            catch (HttpRequestException e)
            {
                return new RespuestaAreaDTO()
                {
                    mensaje = e.Message,
                    icono = "error",
                };

            }

        }

        /// <summary>
        /// Nos conectamos directamente con el API para enviar nuestra edicion al API   
        /// </summary>
        /// <param name="id">ID AREA</param>
        /// <param name="areaCreacionDTO">DTO </param>
        /// <returns></returns>

        [HttpPut]
        public async Task<ActionResult<RespuestaAreaDTO>> EditarArea([FromRoute] int id, [FromBody] AreaCreacionDTO areaCreacionDTO)
        {
            var tokenClaim = HttpContext.User.Claims.Where(x => x.Type == "Token").FirstOrDefault();
            if (tokenClaim == null)
            {
                ///Enviar mensaje de error
                return Json("No se encuentra el TOKEN");
            }


            //Enviar al api la informacion
            HttpClient client = localServiceSSL.VotarSSL(tokenClaim.Value);
            var url = _configuration.GetValue<string>("ConnectionStrings:API") + "/api/areas/" + id;
            try
            {
                string jsonArea = JsonConvert.SerializeObject(areaCreacionDTO);
                var content = new StringContent(jsonArea, System.Text.Encoding.UTF8, "application/json");
                var response = await client.PutAsync(url, content);
                if (response.IsSuccessStatusCode)
                {
                    string responseBody = await response.Content.ReadAsStringAsync();
                    var areaRespuestaDTO = JsonConvert.DeserializeObject<RespuestaAreaDTO>(responseBody);
                    return areaRespuestaDTO;
                }
                else
                {
                    return new RespuestaAreaDTO()
                    {
                        mensaje = "404",
                        codigoEstatus = 404,
                        icono = "info",
                    };
                }
            }
            catch (HttpRequestException e)
            {
                return new RespuestaAreaDTO()
                {
                    mensaje = e.Message,
                    icono = "error",
                };

            }
        }


        /// <summary>
        /// Funcion para eliminar un area enviamos al API
        /// </summary>
        /// <param name="id">id del area</param>
        /// <returns></returns>
        [HttpDelete]
        public async Task<ActionResult<RespuestaAreaDTO>> Delete(int id)
        {
            var tokenClaim = HttpContext.User.Claims.Where(x => x.Type == "Token").FirstOrDefault();
            if (tokenClaim == null)
            {
                ///Enviar mensaje de error
                return Json("No se encuentra el TOKEN");
            }


            HttpClient client = localServiceSSL.VotarSSL(tokenClaim.Value);

            string baseAPI = _configuration.GetValue<string>("ConnectionStrings:API");

            string url = baseAPI + "/api/areas/?id=" + id;
            var response = await client.DeleteAsync(url);
            var r = await response.Content.ReadAsStringAsync();
            if (r != null)
            {
                RespuestaAreaDTO oAreaRespuestaDTO = JsonConvert.DeserializeObject<RespuestaAreaDTO>(r);
                return oAreaRespuestaDTO;
            }
            else
            {
                return
                new RespuestaAreaDTO()
                {
                    icono = "error",
                    codigoEstatus = 404,
                    mensaje = "Fallamos en al conectarnos con el api"
                };
            }

        }
    }
}

SalaJuntasFrontend/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SalaJuntasFrontend.Models.DTOS.Login;
using SalaJuntasFrontend.Servicios;
using System.Security.Claims;

namespace SalaJuntasFrontend.Controllers
{
    public class LoginController : Controller
    {
        public HttpsLocalService localServiceSSL = new HttpsLocalService();
        private readonly IConfiguration configuration;

        public LoginController(IConfiguration configuration)
        {
            this.configuration = configuration;
        }

        // GET: LoginController
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Acesso
        /// </summary>
        /// <param name="credenciales"></param>
        /// <returns></returns>
        public async Task<ActionResult> validarUsuario(CredencialesAcceso credenciales)
        {

            if (credenciales.Email != "" && credenciales.Password != "")
            {
                //Hacemos una peticion para logearse
                string domain = configuration.GetValue<string>("ConnectionStrings:API");
                string url = domain + "/api/cuentas/login";

                HttpClient client = localServiceSSL.VotarSSL();

                var jsonCredenciales = JsonConvert.SerializeObject(credenciales);

                var content = new StringContent(jsonCredenciales, System.Text.Encoding.UTF8, "application/json");

                var send = await client.PostAsync(url, content);

                var respuesta = await send.Content.ReadAsStringAsync();

                if (send.IsSuccessStatusCode)
                {
                    //Deserializa

                    var rspToken = JsonConvert.DeserializeObject<RespuestaAutenticacionDTO>(respuesta);

                    var claims = new List<Claim>
                            {
                                new Claim("Token", rspToken.Token),
                                new Claim("UserName", rspToken.UserName),
                                new Claim("TipoUsuario", rspToken.TipoUsuarioPublico),
                                new Claim(ClaimTypes.Role , rspToken.TipoUsuarioClave )
                            };
                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                    ///Lo dejamos pasar
                    return RedirectToAction("Index", "Agenda");
                }
                else
                {
                    //Llave - Valor
                    ModelState.AddModelError("loginErrors", respuesta);
                    return View("Index");
                }

            }
            return Index();

        }

        // GET: LoginController/Create
        public async Task<IActionResult> Salir()
        {

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index", "Agenda");
        }



    }
}

SalaJuntasFrontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Tzolkin</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fullcalendar/main.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="/css/layout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SalaJuntasFrontend.styles.css" asp-append-version="true" />
    @RenderSection("Styles",required:false)

</head>
<body>
    <header>
        @{
            var actualYear = DateTime.Now.ToString("yyyy");
            string UserName = "Invitado";
            bool token = false;
            string role = "";
        }
        @if (User.IsInRole("supersu") || User.IsInRole("admin") || User.IsInRole("moderador") || User.IsInRole("cliente"))
        {
            UserName = User.Claims.Where(x => x.Type == "UserName").FirstOrDefault().Value;
            token = true;
            role = User.Claims.Where(x => x.Type == "TipoUsuario").FirstOrDefault().Value;
        }

        <input type="hidden" id="authorize" value="@token" />
        <input type="hidden" id="userName" value="@UserName" />

        <nav class="navbar fondo-verde-primary">
            <div class="container-fluid">
                <div class="d-flex justify-content-center">
                    <a class="navbar-brand" asp-controller="Agenda" asp-action="Index"><img height="60px" src="~/lib/images/logosGiotex/whiteFullLogo.png"></img></a>
                </div>
                <div class="d-flex justify-content-left">
                    <a class="navbar-brand" asp-controller="Agenda" asp-action="Index"> <h3 class="color-text-primario" style="font-family:'Future Friends'">&nbsp;&nbsp;Tzolk'in</h3></a> <a class="navbar-brand" asp-controller="Agenda" asp-action="Index"><h1 class="color-text-primario text-banner"> "La cuenta de los días" </h1></a>
                </div>
                <button class="navbar-toggler bg-light" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    @UserName
                    <i class="fa-solid fa-shuffle"></i>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <h3 class="offcanvas-title" id="offcanvasNavbarLabel">¡Hola! @UserName <br /> Bienvenido </h3>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <form class="d-flex" role="search">
                        </form>
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                @*<a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="Home">Inicio</a>*@
                            </li>
                            @if (User.IsInRole("cliente"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        @UserName
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" asp-action="Salir" asp-controller="Login">Cerrar Sesion</a></li>
                                    </ul>
                                </li>
                            }


                            @if (User.IsInRole("moderador"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Departamentos" asp-action="Index">Departamentos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Areas" asp-action="Index">Areas</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        @UserName
                                    </a>
                                    <ul class="dropdown-menu">

                                        <li><a class="dropdown-item" asp-action="Salir" asp-controller="Login">Cerrar Sesion</a></li>
                                    </ul>
                                </li>
                            }

                            @if (User.IsInRole("supersu") || User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Departamentos" asp-action="Index">Departamentos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Areas" asp-action="Index">Areas</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        @UserName
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" asp-action="Salir" asp-controller="Login">Cerrar Sesion</a></li>
                                    </ul>
                                </li>
                            }

                            @if (!User.IsInRole("supersu") && !User.IsInRole("admin") && !User.IsInRole("moderador") && !User.IsInRole("cliente"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="Home">Inicio</a>
                                    <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="Login">Iniciar Sesion / Crear Cuenta</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

        @*        <nav class="navbar navbar-expand-lg navbar-light fondo-gris-primary">
            <div class="container-fluid">
            <img height="60px" width="60px" src="~/lib/images/solMayads.png"></img>
            <a class="navbar-brand" asp-controller="Agenda" asp-action="Index"> <h3 class="color-text-primario" style="font-family:'Future Friends'">&nbsp;&nbsp;Tzolk'in</h3></a> <h1 class="color-text-primario text-banner"> "La cuenta de los días" </h1>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <a class="nav-link active" style="visibility : hidden" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" style="visibility : hidden" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" style="visibility : hidden" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a style="visibility : hidden" class="dropdown-item" href="#">Action</a></li>
            <li><a style="visibility : hidden" class="dropdown-item" href="#">Another action</a></li>
            <li><hr style="visibility : hidden" class="dropdown-divider"></li>
            <li><a style="visibility : hidden" class="dropdown-item" href="#">Something else here</a></li>
            </ul>
            </li>
            <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" style="visibility : hidden" aria-disabled="true">Disabled</a>
            </li>
            </ul>
            <form class="d-flex">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <a class="nav-link active text-light" asp-controller="Home" asp-action="Index">Inicio</a>
            </li>
            @if (User.IsInRole("supersu") || User.IsInRole("admin") || User.IsInRole("moderador"))
            {

            <li class="nav-item">
            <a class="nav-link text-light" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
            </li>
            <li class="nav-item">
            <a class="nav-link text-light" asp-controller="Departamentos" asp-action="Index">Departamentos</a>
            </li>
            <li class="nav-item">
            <a class="nav-link text-light" asp-controller="Areas" asp-action="Index">Areas</a>
            </li>
            }
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle bg-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            @{
            string UserName = "Invitado";
            }

            @if (User.IsInRole("supersu") || User.IsInRole("admin") || User.IsInRole("moderador") || User.IsInRole("cliente"))
            {
            UserName = User.Claims.Where(x => x.Type == "UserName").FirstOrDefault().Value;

            }

            @UserName

            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            @if (User.IsInRole("supersu") || User.IsInRole("admin") || User.IsInRole("moderador") || User.IsInRole("cliente"))
            {
            <li><a class="dropdown-item" href="#">Mi Perfil</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" asp-action="Salir" asp-controller="Login">Cerrar Sesion</a></li>
            }
            else
            {
            <li><a class="dropdown-item" href="#">Registrarse</a></li>
            <li><a class="dropdown-item" href="#">Iniciar Sesion</a></li>

            }
            </ul>
            </li>
            </ul>
            </form>
            </div>
            </div>
            </nav>*@
    </header>
    <div class="container gradient-custom-2">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            ©@actualYear Giotex S.A o sus afiliados
           <a asp-area="" asp-controller="Agenda" asp-action="Index"> Tzolk'in'</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/fullcalendar/main.min.js"></script>
    <script src="~/lib/fullcalendar/locales-all.min.js"></script>
    <script src="~/lib/momentjs/moment.js"></script>
    <script src="~/lib/momentjs/lenguaje/es.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>
    <script src="~/lib/fontawesome/js/all.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SalaJuntasFrontend/Views/Shared/_Modal.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}
@RenderSection("Styles")
<!-- Scrollable modal -->
<div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title"> @RenderSection("title") </h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            @RenderSection("body")
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            @RenderSection("buttons")
        </div>
    </div>
</div>

@RenderSection("Scripts")