SalaJuntasFrontend/Controllers/AgendaController.cs
using ApiSalaJuntas.Model.DTOS.Areas;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SalaJuntasFrontend.Models.DTOS.ViewsModel;

namespace SalaJuntasFrontend.Controllers
{
    public class AgendaController : Controller
    {
        private readonly IMapper mapper;
        private readonly IConfiguration configuration;

        public AgendaController(IMapper mapper, IConfiguration configuration)
        {
            this.mapper = mapper;
            this.configuration = configuration;
        }

        public IActionResult Index()
        {
            AreasController areasController = new AreasController(mapper, configuration);
            //Realizamos una peticion para obtener todas las salas
            var todasSalas = (dynamic)areasController.TodosAreas().Result.Result;

            List<AreaDTO> jsonSalas = todasSalas.Value.Data;

            var areasViewModel = new AreasViewModel();

            if (jsonSalas != null)
            {
                areasViewModel.areas = jsonSalas;
                areasViewModel.estatus = "success";
            }

            areasViewModel.estatus = "error";

            return View(areasViewModel);
        }
    }
}

SalaJuntasFrontend/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SalaJuntasFrontend.Models;
using System.Diagnostics;

namespace SalaJuntasFrontend.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SalaJuntasFrontend/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
}

<div class="text-center">
    <h1 class="display-4">¡Bienvenido!</h1>
    <h5>Te presentamos <a href="@Url.Action("Index","Agenda")">Tzolk'in</a> por <b>Giotex</b> </h5>
    <p>
        "Tzol'kin" por <b>Giotex</b>, es una <i>Aplicacion Web</i> que te servira para hacer <u>reservaciones</u> en las diferentes salas de la empresa. Esto
        ayudara a todos los colaboradores a observar qué actividades estaran ocupando las diferentes salas y evitar esos molestos choques de horario.
    </p>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="display-6">¿Necesitas ayuda? Da click a la imagen y sigue las instrucciones</h1>
                <a href="http://10.0.100.25:8004/s/f2okRkf7JXpgEoF" target="_blank">
                    <div>
                        <img src="~/lib/images/alterarEvento.jpg" height="300px" width="300px"/>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>